// frontend_vue/src/components/Footer.vue
<template>
  <footer class="footer-custom">
    <div class="footer-left">
      <span class="footer-logo"><i class="bi bi-asterisk" /> clipsai</span>
      <span class="footer-separator">|</span>
      <span class="footer-copy">© 2026 Hecho con <i class="bi bi-heart-fill" style="color:#EF4444; font-size:0.75rem" /> por clipsai • Spark Admin</span>
    </div>
    <div class="footer-right">
      <ul class="footer-links">
        <li><RouterLink to="/dashboard" class="footer-link">Overview</RouterLink></li>
        <li><RouterLink to="/clips" class="footer-link">Biblioteca</RouterLink></li>
        <li><a href="#" class="footer-link" @click.prevent> Ayuda </a></li>
        <li><a href="#" class="footer-link" @click.prevent> Status <span class="status-dot" /></a></li>
      </ul>
    </div>
  </footer>
</template>

// frontend_react/src/components/Footer.tsx
export default function Footer() {
  return (
    <footer className="footer-custom">
      <div className="footer-left">
        <span className="footer-logo">
          <i className="bi bi-asterisk" /> clipsai
        </span>
        <span className="footer-separator">|</span>
        <span className="footer-copy">
          © 2026 Hecho con <i className="bi bi-heart-fill text-danger" style={{ color: '#EF4444', fontSize: '0.75rem' }} /> por clipsai • Spark Admin
        </span>
      </div>
      <div className="footer-right">
        <ul className="footer-links">
          <li>
            <a href="/dashboard" className="footer-link">
              Overview
            </a>
          </li>
          <li>
            <a href="/clips" className="footer-link">
              Biblioteca
            </a>
          </li>
          <li>
            <a href="#" className="footer-link">
              Ayuda
            </a>
          </li>
          <li>
            <a href="#" className="footer-link">
              Status <span className="status-dot" />
            </a>
          </li>
        </ul>
      </div>
    </footer>
  )
}
